name: Anchore Docker Scan

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: kkacsh321/cfntools:test-anchore
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "kkacsh321/cfntools:test-anchore"
          fail-build: false
          severity-cutoff: "medium"
          acs-report-enable: false

      - name: grype scan JSON results
        run: |
          jq -r '["ID", "Severity", "Description", "Fixed In Version"], (.matches[].vulnerability | {id: .id, severity:.severity, description: .description, fixedinversion: .fixedInVersion}) | flatten | @csv' ./vulnerabilities.json

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: Anchore-Report
          path: ./vulnerabilities.json
          retention-days: 7
